// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcxxyk4iSbmqPrpnG8LoQMpLwM84LcbZo',
    appId: '1:864917682311:android:51d9698c1304e325c82022',
    messagingSenderId: '864917682311',
    projectId: 'myreminder-93de0',
    storageBucket: 'myreminder-93de0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoRaqrdbH2U92DKQzhpoHgz6CpMPyhfb8',
    appId: '1:864917682311:ios:23fe0d5ef7510354c82022',
    messagingSenderId: '864917682311',
    projectId: 'myreminder-93de0',
    storageBucket: 'myreminder-93de0.firebasestorage.app',
    iosBundleId: 'com.myre.myreminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmPY_mS7XO6BW5POCt7Wpg7pKpLtCHZ6I',
    appId: '1:864917682311:web:a932547678bf4c37c82022',
    messagingSenderId: '864917682311',
    projectId: 'myreminder-93de0',
    authDomain: 'myreminder-93de0.firebaseapp.com',
    storageBucket: 'myreminder-93de0.firebasestorage.app',
    measurementId: 'G-CMRVZ3ES6E',
  );
}
